{% set name = "hg-git" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 96a9c28b832374f5422177580080c6751639cdc53940fad21f3cbe34acac32d7

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.9
    - mercurial
    - dulwich >=0.21.6,<0.23.0

test:
  imports:
    - hggit
  commands:
    - hg version -v
    - hg debuginstall
    - hg help -e hggit --config "extensions.hggit="

about:
  home: https://wiki.mercurial-scm.org/HgGit
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: Push to and pull from a Git repository using Mercurial
  doc_url: https://wiki.mercurial-scm.org/HgGit
  dev_url: https://foss.heptapod.net/mercurial/hg-git/

extra:
  recipe-maintainers:
    - paugier
