{% set name = "hg-git" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3911833962eb9c899c6bea8fb49666c82f211b124d0840beb6ad95e23a4621b6

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mercurial
    - dulwich >=0.19.0

test:
  imports:
    - hggit
  commands:
    - hg help -e hggit --config "extensions.hggit="

about:
  home: https://hg-git.github.io/
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: Push to and pull from a Git repository using Mercurial
  doc_url: https://hg-git.github.io/
  dev_url: https://dev.heptapod.net/mercurial/hg-git/

extra:
  recipe-maintainers:
    - paugier
